# Read the documentation: https://symfony.com/doc/current/bundles/FOSCKEditorBundle/index.html

twig:
    form_themes:
        - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
fos_ck_editor:
    input_sync: true
    default_config: base_config
    configs:
        base_config:
            toolbar:
            - { name: "document", items: ['Print','-', 'Templates'] }
            - '/'
            - { name: "styles", items: ['Bold', 'Italic', 'Underline', 'Strike','-', 'Subscript', 'Superscript','-', 'NumberedList', 'BulletedList','-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock','-', 'BidiLtr', 'BidiRtl','-', 'Link', 'Unlink','-', 'Image', 'Smiley', 'SpecialChar'] }
            - '/'
            - { name: "styles2", items: ['FontSize','-','TextColor','BGColor']}