vich_uploader:
    db_driver: orm

    mappings:
        home-text_image:
            uri_prefix: /img/homeTexts
            upload_destination: '%kernel.project_dir%/public/assets/images/homeTexts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer