vich_uploader:
    db_driver: orm

    mappings:
        text_image:
            delete_on_remove: true
            delete_on_update: true
            uri_prefix: /assets/images/homeTexts
            upload_destination: '%kernel.project_dir%/public/assets/images/homeTexts'
            namer: Vich\UploaderBundle\Naming\UniqidNamer