version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: my_secret_pw_shh
      MYSQL_DATABASE: test_db
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
      - "9906:3306"
  web:
    build: .
    container_name: web
    depends_on:
      - db
      - fakesmtp
    environment:
      DATABASE_URL: mysql://devuser:devpass@db/test_db
      MAILER_URL: smtp://fakesmtp:25
    volumes:
      - ./:/var/www/html/
      - ./.config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "8100:80"
    stdin_open: true
    tty: true
  fakesmtp:
    image: djfarrelly/maildev
    ports:
      - 1080:80
      - 1025:25
